#!/bin/bash

#ln command
ln="ln -nfs"

$ln ~/.dotfiles/bash_profile ~/.bash_profile
$ln ~/.dotfiles/vimrc ~/.vimrc
$ln ~/.dotfiles/gitconfig ~/.gitconfig
git config --global core.excludesfile ~/.dotfiles/gitignore-global
source ~/.bash_profile

#install Vundle
if [[ ! -d ~/.vim/bundle/vundle ]]; then
  git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/vundle
fi

# run vim setup
vim -s '~/.dotfiles/script/setup.vim'
